apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: kluster-base
  source:
    path: kubernetes/argocd-kluster/argocd
    repoURL: https://github.com/Uptime-Formation/corrections_tp.git
    targetRevision: HEAD

